name: Build
on:
  push:
  workflow_call:
    outputs:
      JDK_VERSION:
        value: ${{ jobs.build.outputs.JDK_VERSION }}

jobs:
  build:
    uses: malkusch/github/.github/workflows/maven-build.yml@master
    secrets: inherit
    with:
      UNIT_TESTS_ENABLED: false
      INTEGRATION_TESTS_ENABLED: false
